package com.reconx;

import java.io.FileWriter;
import java.io.IOException;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javafx.scene.control.Alert;
import javafx.scene.control.Alert.AlertType;

public class ReportManager {

    public static void saveReport(String target, String data) {
        // Create a unique filename based on the target
        String timestamp = LocalDateTime.now().format(DateTimeFormatter.ofPattern("yyyyMMdd_HHmmss"));
        String filename = "ReconX_" + target.replace(".", "_") + "_" + timestamp + ".txt";

        try (FileWriter writer = new FileWriter(filename)) {
            writer.write("=========================================\n");
            writer.write("       RECONX INTELLIGENCE REPORT        \n");
            writer.write("=========================================\n");
            writer.write("TARGET   : " + target + "\n");
            writer.write("SCANNED  : " + LocalDateTime.now() + "\n");
            writer.write("-----------------------------------------\n");
            writer.write(data);
            writer.write("\n=========================================\n");
            writer.write("Generated by ReconX OSINT Tool\n");

            // Show success popup
            showAlert("Success", "Report saved as: " + filename);

        } catch (IOException e) {
            showAlert("Error", "Could not save report: " + e.getMessage());
        }
    }

    private static void showAlert(String title, String message) {
        Alert alert = new Alert(AlertType.INFORMATION);
        alert.setTitle(title);
        alert.setHeaderText(null);
        alert.setContentText(message);
        alert.showAndWait();
    }
}