package com.reconx;

import java.awt.Desktop;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Optional;
import javafx.scene.control.Alert;
import javafx.scene.control.Alert.AlertType;
import javafx.scene.control.ButtonType;
import javafx.stage.FileChooser;
import javafx.stage.Window;

public class ReportManager {

    private static File lastDirectory = new File(System.getProperty("user.dir"));

    public static void saveReport(Window owner, String target, String data) {
        // Create a default unique filename based on the target
        String timestamp = LocalDateTime.now().format(DateTimeFormatter.ofPattern("yyyyMMdd_HHmmss"));
        String defaultFilename = "ReconX_" + target.replace(".", "_") + "_" + timestamp + ".txt";

        FileChooser fileChooser = new FileChooser();
        fileChooser.setTitle("Save ReconX Report");
        fileChooser.setInitialFileName(defaultFilename);
        fileChooser.setInitialDirectory(lastDirectory);
        fileChooser.getExtensionFilters().add(new FileChooser.ExtensionFilter("Text Files", "*.txt"));

        File file = fileChooser.showSaveDialog(owner);

        if (file != null) {
            lastDirectory = file.getParentFile();
            try (FileWriter writer = new FileWriter(file)) {
                writer.write("=========================================\n");
                writer.write("       RECONX INTELLIGENCE REPORT        \n");
                writer.write("=========================================\n");
                writer.write("TARGET   : " + target + "\n");
                writer.write("SCANNED  : " + LocalDateTime.now() + "\n");
                writer.write("-----------------------------------------\n");
                writer.write(data);
                writer.write("\n=========================================\n");
                writer.write("Generated by ReconX OSINT Tool\n");

                // Show success popup with Open Folder option
                showSuccessAlert(file);

            } catch (IOException e) {
                showAlert("Error", "Could not save report: " + e.getMessage());
            }
        }
    }

    public static void openReportsFolder() {
        openFolder(lastDirectory);
    }

    private static void showSuccessAlert(File file) {
        Alert alert = new Alert(AlertType.INFORMATION);
        alert.setTitle("Success");
        alert.setHeaderText("Report Saved Successfully");
        alert.setContentText("Report saved to:\n" + file.getAbsolutePath());

        ButtonType openFolderBtn = new ButtonType("Open Folder");
        ButtonType closeBtn = new ButtonType("Close", ButtonType.CLOSE.getButtonData());

        alert.getButtonTypes().setAll(openFolderBtn, closeBtn);

        Optional<ButtonType> result = alert.showAndWait();
        if (result.isPresent() && result.get() == openFolderBtn) {
            openFolder(file.getParentFile());
        }
    }

    private static void openFolder(File folder) {
        try {
            if (Desktop.isDesktopSupported()) {
                Desktop.getDesktop().open(folder);
            } else {
                showAlert("Error", "Desktop is not supported on this system.");
            }
        } catch (IOException e) {
            showAlert("Error", "Could not open folder: " + e.getMessage());
        }
    }

    private static void showAlert(String title, String message) {
        Alert alert = new Alert(AlertType.INFORMATION);
        alert.setTitle(title);
        alert.setHeaderText(null);
        alert.setContentText(message);
        alert.showAndWait();
    }
}